### ISSUE TITLE
Inconsistent execution ld sp,ix

### ISSUE THREAD

**Issue by retrodeluxe** [anotherlin/z80emu#12]
I am trying to use this emulator to test a compiler and it looked it was working fine,
but now I am facing some issues when dealing with the stack.

"ld sp, ix" behaves inconsistently depending on the context; which results in wrong sp value.

**Comment by retrodeluxe** [comment]
It looks like a problem the decoding of DD prefixed instructions and the use of dd_register_table.

**Comment by retrodeluxe** [comment]
nevermind

**Comment by anotherlin** [comment]
Hello,

Can you be more precise about the issue?
I will soon (hopefully) rework on my emulator project and I will fix all the bugs in z80emu.

Thank you.

Best regards,
