### ISSUE TITLE
Mode2 Interrupts

### ISSUE THREAD

**Issue by rootednode** [anotherlin/z80emu#7]
It looks like the mode 2 interrupts implementation is bad. It is actually jumping to the location generated by the interrupt instead of reading the actual address to jump to from that location. I made some modifications to make it dereference that interrupt vector and it seems to work great.

**Comment by anotherlin** [comment]
Hi,

I've double checked, indeed I've made a gross mistake. The 16-bit vector is used as is, instead of dereferencing it and jumping to the 16-bit address read. I'll correct this bug. 
Thank you for reporting this issue. I'm surprised it hasn't been noticed before.

Best regards,

**Comment by anotherlin** [comment]
Hi,

I've fixed the code, just added the dereferencing.
Can you please check it works for you?
I'll update the README then.
Thank you.

Best regards,

**Comment by anotherlin** [comment]
Seems it works now. I'll update the readme.txt and make a new release. Thank you.
